### ISSUE TITLE
ERR unknown command 'EXHGETALL2'

### ISSUE THREAD

**Issue by zhaoyibo** [aliyun/alibabacloud-tairjedis-sdk#2]
`com.aliyun.tair.ModuleCommand#EXHGETALL` 内的值为 `EXHGETALL2`

https://github.com/aliyun/alibabacloud-tairjedis-sdk/blob/6d0987f03a9a97195d3ab4c3ccca29bed93ca795/src/main/java/com/aliyun/tair/ModuleCommand.java#L46

但是 `EXHGETALL2` 命令在 tair 上并找不到。

![92322A0D-524E-44DE-8ECF-2E5BC6B3DAAE](https://user-images.githubusercontent.com/11988080/99387805-92dae780-290f-11eb-91c4-d8f9415924c1.png)

用的是你们阿里云 Redis 5.0 企业版。

**Comment by yangbodong22011** [comment]
感谢提出此问题，这里是我们的问题，我将修复

**Comment by yangbodong22011** [comment]
@zhaoyibo fixed, thanks.
